sudo: false

language: node_js
node_js:
  - 14

cache:
  directories:
    - $HOME/node_modules
    - $HOME/client/node_modules

install:
  - npm ci
  - cd client && npm ci

script:
  - npm test
  - npm run dev